Repository cs130-w21/19, pull requests merged in 2021-03, with the labels that each got.

#69 Front end testing
  .travis.yml
  client/package.json
  client/src/App.js
  client/src/components/Portfolio.jsx
  client/src/components/Portfolio.test.js
  client/src/components/Watchlist.test.js
  client/src/components/buySellWidget.test.js
  client/src/components/loginForm.test.js
  client/src/components/searchNavbar.jsx
  client/src/pages/chart.test.js
  client/src/setupTests.js
  client/yarn.lock
  package-lock.json
  server/package-lock.json
  server/src/marketData/marketPrice.js
  server/test/integration/marketPrice.test.js
Labels: frontend

#76 Cleaner UI
  client/src/App.js
  client/src/components/Portfolio.jsx
  client/src/components/Portfolio.test.js
  client/src/components/common/table.jsx
  client/src/components/navibar.jsx
  client/src/pages/HistoryTable.jsx
  client/src/pages/chart.jsx
  client/src/pages/myHistory.jsx
  client/src/pages/myProfile.jsx
  client/src/utils.js
Labels: bug, frontend

#78 User onboarding
  client/package.json
  client/src/App.js
  client/src/__tests__/Portfolio.test.js
  client/src/__tests__/Watchlist.test.js
  client/src/__tests__/buySellWidget.test.js
  client/src/__tests__/chart.test.js
  client/src/__tests__/loginForm.test.js
  client/src/components/Chart.js
  client/src/components/GrowthChart.jsx
  client/src/components/HistoryTable.jsx
  client/src/components/Portfolio.jsx
  client/src/components/SearchBar.jsx
  client/src/components/StockSelector.jsx
  client/src/components/Tutorial.jsx
  client/src/components/Watchlist.jsx
  client/src/components/buySellWidget.jsx
  client/src/components/common/Form.jsx
  client/src/components/loginForm.jsx
  client/src/components/myHistory.jsx
  client/src/components/navibar.jsx
  client/src/components/registerForm.jsx
  client/src/components/searchNavbar.jsx
  client/src/pages/chart.jsx
  client/src/pages/myProfile.jsx
  client/src/pages/welcome.jsx
  client/src/services/dummyHistory.js
  client/yarn.lock
Labels: frontend

#65 add c8 codecov + CI step.
  .gitignore
  .travis.yml
  README.md
  client/yarn.lock
  package.json
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/chartingRoutes.js
  server/src/db/dbClient.js
  server/src/searchRoutes.js
  server/src/tradingRoutes.js
  server/src/watchlistRoutes.js
  server/test/integration/search.test.js
  server/test/unit/authMiddleware.test.js
  server/test/unit/marketPrice.test.js
  yarn.lock
Labels: Infra, backend

#79 Live data
  client/src/components/Chart.js
  client/src/pages/chart.jsx
  client/src/services/chartingService.js
  client/src/utils.js
Labels: frontend
