Repository cs130-w21/19, pull requests merged in 2021-02, with the labels that each got.

#23 add trading routes
  .npmignore
  package-lock.json
  package.json
  server.js
  src/db/addDummyData.sql
  src/db/dbClient.js
  src/db/schemas.js
  src/marketData/marketPrice.js
  src/tradingRoutes.js
  src/utils/markets.js
  test/unit_tests/trading.test.js
Labels: backend, story

#32 ci: fix travis not breaking when tests fail
  .travis.yml
Labels: Infra, bug

#25 Login feature - Frontend
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/chart.jsx
  client/src/components/common/Form.jsx
  client/src/components/common/input.jsx
  client/src/components/loginForm.jsx
  client/src/components/logout.jsx
  client/src/components/navibar.jsx
  client/src/components/registerForm.jsx
  client/src/components/support.jsx
  client/src/components/watchlist.jsx
  client/src/config.json
  client/src/index.js
  client/src/services/authService.js
  client/src/services/httpService.js
  client/src/services/logService.js
  client/yarn.lock
  package-lock.json
  package.json
  src/accountRoutes.js
  src/db/dbClient.js
Labels: frontend

#37 add buy sell widget and fix react bootstrap problem
  client/package.json
  client/src/App.js
  client/src/components/buySellWidget.jsx
  client/src/components/chart.jsx
  client/src/config.json
  client/src/pages/chart.jsx
  client/src/services/tradingService.js
  client/src/styles/app.css
  client/src/styles/buySellWidget.css
  client/src/utils.js
  package-lock.json
  package.json
Labels: frontend, story

#42 add automatic apidoc generation & hosting
  .gitignore
  .travis.yml
  apidoc.json
  package-lock.json
  package.json
  server.js
  src/accountRoutes.js
  src/auth/authMiddleware.js
  src/tradingRoutes.js
Labels: Infra, backend

#38 add view portfolio feature
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/Chart.js
  client/src/components/Portfolio.jsx
  client/src/components/buySellWidget.jsx
  client/src/components/loginForm.jsx
  client/src/components/navibar.jsx
  client/src/components/piechart.jsx
  client/src/components/support.jsx
  client/src/components/watchlist.jsx
  client/src/pages/chart.jsx
  client/src/pages/myProfile.jsx
  client/src/pages/welcome.jsx
  client/src/services/portfolioService.js
  client/src/utils.js
  package-lock.json
  package.json
  server.js
  src/accountRoutes.js
  src/db/dbClient.js
  src/portfolioRoutes.js
  src/utils/markets.js
Labels: backend, frontend

#44 add search route (backend)
  .gitignore
  package-lock.json
  package.json
  server.js
  src/accountRoutes.js
  src/portfolioRoutes.js
  src/search/nasdaq_screener_stocks.csv
  src/search/searchEngine.js
  src/searchRoutes.js
  src/tradingRoutes.js
Labels: backend

#35 [WIP] test: setup Integration testing architecture and add accounts & trading tests
  .travis.yml
  ci/run_test_db.sh
  package-lock.json
  package.json
  server.js
  src/accountRoutes.js
  src/db/dbClient.js
  src/search/searchEngine.js
  src/tradingRoutes.js
  src/utils/markets.js
  test/integration/accounts.test.js
  test/integration/trading.test.js
  test/unit/trading.test.js
  test/utils/userManagement.js
Labels: Infra, backend

#53 use separate server and client dirs (project structure)
  .npmignore
  .travis.yml
  Procfile
  README.md
  REPO_CONVENTIONS.md
  ci/create-zip-bundle.sh
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/yarn.lock
  input.txt
  package-lock.json
  package.json
  server/apidoc.json
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/accountRoutes.js
  server/src/auth/authMiddleware.js
  server/src/auth/passportConfig.js
  server/src/db/addDummyData.sql
  server/src/db/dbClient.js
  server/src/db/schemas.js
  server/src/marketData/marketPrice.js
  server/src/portfolioRoutes.js
  server/src/search/nasdaq_screener_stocks.csv
  server/src/search/searchEngine.js
  server/src/searchRoutes.js
  server/src/tradingRoutes.js
  server/src/utils/markets.js
  server/src/utils/validation.js
  server/src/watchlistRoutes.js
  server/test/integration/accounts.test.js
  server/test/integration/trading.test.js
  server/test/unit/trading.test.js
  server/test/utils/userManagement.js
Labels: backend, bug, frontend

#49 Add search frontend PR
  README.md
  client/package.json
  client/src/App.js
  client/src/components/SearchBar.jsx
  client/src/components/StockSelector.jsx
  client/src/components/buySellWidget.jsx
  client/src/components/navibar.jsx
  client/src/components/searchNavbar.jsx
  client/src/pages/chart.jsx
  client/src/services/tickerService.js
  client/src/utils.js
  client/yarn.lock
  package-lock.json
  package.json
Labels: frontend

#58 realtime stock trading & live data backend
  .gitignore
  .travis.yml
  README.md
  client/src/components/buySellWidget.jsx
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/accountRoutes.js
  server/src/chartingRoutes.js
  server/src/db/dbClient.js
  server/src/db/schemas.js
  server/src/marketData/finnhub.js
  server/src/marketData/marketPrice.js
  server/src/marketData/realtimeStream.js
  server/src/marketData/subscriptionManager.js
  server/src/search/nasdaq_screener_stocks.csv
  server/src/search/searchEngine.js
  server/src/searchRoutes.js
  server/src/tradingRoutes.js
  server/test/integration/accounts.test.js
  server/test/integration/charting.test.js
  server/test/integration/history.test.js
  server/test/integration/realtimeStream.test.js
  server/test/integration/trading.test.js
  server/test/unit/SubscriptionManager.test.js
  server/test/unit/trading.test.js
  server/test/utils/userManagement.js
Labels: backend

#60 backend setup for realtime portfolio + more unit & int tests
  .gitignore
  server/package.json
  server/server.js
  server/src/db/dbClient.js
  server/src/marketData/marketPrice.js
  server/src/marketData/realtimeStream.js
  server/src/portfolio/portfolio.js
  server/src/portfolioRoutes.js
  server/src/search/searchEngine.js
  server/test/integration/charting.test.js
  server/test/integration/marketPrice.test.js
  server/test/integration/portfolio.test.js
  server/test/integration/realtimeStream.test.js
  server/test/integration/setupTest.js
  server/test/integration/trading.test.js
  server/test/unit/marketPrice.test.js
  server/test/unit/portfolio.test.js
  server/test/utils/testTickers.js
Labels: backend
